var highlight = require('../')(require('../all'))
var marked = require('marked')
var fs = require('fs')
var src = fs.readFileSync(__dirname+'/../readme.md','utf8')
console.log(marked(src, { highlight: highlight }))
